
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package backEnd.analisisLexSintax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NamElse = 31;
  public static final int EndCom = 22;
  public static final int Mas = 12;
  public static final int PrintS = 10;
  public static final int Mayor = 16;
  public static final int Entero = 28;
  public static final int And = 19;
  public static final int PrintN = 9;
  public static final int Identificador = 30;
  public static final int Booleano = 26;
  public static final int NamString = 5;
  public static final int CorCerrado = 33;
  public static final int Coma = 25;
  public static final int NamWhile = 8;
  public static final int Or = 20;
  public static final int Cadena = 27;
  public static final int NamIf = 7;
  public static final int EOF = 0;
  public static final int NamMain = 6;
  public static final int ParAbierto = 23;
  public static final int Por = 14;
  public static final int Decimal = 29;
  public static final int error = 1;
  public static final int BreakCom = 11;
  public static final int Menos = 13;
  public static final int Menor = 17;
  public static final int Asignacion = 21;
  public static final int NamFloat = 3;
  public static final int Igual = 18;
  public static final int NamInt = 2;
  public static final int Div = 15;
  public static final int Diferente = 32;
  public static final int NamBoolean = 4;
  public static final int CorAbierto = 34;
  public static final int ParCerrado = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NamInt",
  "NamFloat",
  "NamBoolean",
  "NamString",
  "NamMain",
  "NamIf",
  "NamWhile",
  "PrintN",
  "PrintS",
  "BreakCom",
  "Mas",
  "Menos",
  "Por",
  "Div",
  "Mayor",
  "Menor",
  "Igual",
  "And",
  "Or",
  "Asignacion",
  "EndCom",
  "ParAbierto",
  "ParCerrado",
  "Coma",
  "Booleano",
  "Cadena",
  "Entero",
  "Decimal",
  "Identificador",
  "NamElse",
  "Diferente",
  "CorCerrado",
  "CorAbierto"
  };
}

